### ISSUE TITLE
As a user, I want the chatbot to correct my typos, so that I don't have to spell everything perfectly

### ISSUE THREAD

**Issue by griffinallen** [Drov3r/COSC-4P02#15]
Names, course codes or general typos 

    Important that it does not attempt to correct names that were spelled correctly 

    Check initial spelling first, then if nothing comes back, try modifying and checking again

**Comment by griffinallen** [comment]
Priority: 8

**Comment by DanielGannage** [comment]
mobile and desktop browsers have autocorrect to handle this
