### ISSUE TITLE
As an admin i want an opening screen before the program is launched. So that resources are used effectively.

### ISSUE THREAD

**Issue by Drov3r** [Drov3r/COSC-4P02#18]

**Comment by Drov3r** [comment]
Priority level: 8
The software should open up to some sort of welcome screen, with either an options menu or (if an executable) an exit button. This screen should also include some element that when interacted with will bring the user to the main screen of the software, allowing them to have their conversation with Chatbot.
The only requirement for this feature is that the main screen exists and can be switched to, otherwise this feature should be able to stand alone.

**Comment by aidanLarock** [comment]
Introductory interface now live with enter chat text area and other buttons with links and features. This will ensure that resources are not used up until the user sends a message and is a nice introductory interface for the user.
