### ISSUE TITLE
As a user I want a main screen to be organized and contain a lot of key features. So that all features are accessible and easy to use

### ISSUE THREAD

**Issue by Drov3r** [Drov3r/COSC-4P02#19]

**Comment by Drov3r** [comment]
Priority Level: 10
The main screen of the application must feature a chat log, a user input bar, a back button and/or menu button, and the functionalities of communication between the user and the chatbot. The user screen should be laid out in a clean and concise format with little to no “clutter”, allowing the user to easily read the conversation with the chatbot and understand the functions behind all interactable elements on the screen.

**Comment by aidanLarock** [comment]
Lots of features such as links to summer games pages and frame rate toggles have been added. Main page is organized and simple to understand and navigate.
