### ISSUE TITLE
As a user, I want to see an animation which indicates that the chatbot is "thinking" or "typing" while I wait for it to answer so that I know the bot is working on an answer.

### ISSUE THREAD

**Issue by Braden-Saunders** [Drov3r/COSC-4P02#29]
Section: 4.8.1
Priority level: 6

"[...] the chatbot should begin thinking about what message it has received, and how it will answer. In some cases, this will be a very quick process, however in other cases the chatbot may need more time, especially when it needs to access a website for its information. In all cases, in the time between when the chatbot receives the message until the chatbot outputs its own, it is important that there is some form of indicator that the chatbot is working, and has not forgotten about the user inquiry. This can be done in the form of a “loading circle”, “animated ellipses”, or any other form that clearly displays the chatbot is working."

**Comment by aidanLarock** [comment]
Added 3 dots (similar to other message systems). This commonality between interfaces should ensure users know what the animation means. It should also mean the user now knows when the bot is formulating a solution to their message.
