### ISSUE TITLE
As a user, I want there to be a menu or settings button so that I can set and change my preferences (e.g. language or theme)

### ISSUE THREAD

**Issue by Braden-Saunders** [Drov3r/COSC-4P02#30]
Section 4.9.1
Priority level: 4

"The idea of the menu option would be to allow the user to set some preferences within the software, and the exit and/or back buttons would be contained within this menu. This is completely optional, however if any of the other optional features are to be implemented then it is highly recommended it is done through the menu."

"The menu would be brought up through a button located on the screen, ideally in a corner. This button should use a typical “menu” or “settings” design, such as a series of bars or a gear."

**Comment by DanielGannage** [comment]
toggle frame rate in settings
