### ISSUE TITLE
As a user, I want there to be method of saving my chat conversation so that I can reference it later.

### ISSUE THREAD

**Issue by Braden-Saunders** [Drov3r/COSC-4P02#31]
Section: 4.11.1
Priority level: 4

"This optional feature of the chatbot would be designed to allow the user to save a record of the conversation with the chatbot for future use, if they needed to be able to remember something it told them or a series of questions. The feature would work by either accessing the user’s clipboard and saving the message there, as though the user were to simply “copy” it, allowing pasting wherever the user chooses, or alternatively the feature could temporarily provide the chat log in a copy-friendly format, allowing the user to select the text they find valuable and copy it themselves."

There are a few ways we could accomplish this:
- A button to copy the entire chat log to your clipboard
- A button to download the chat log as a .txt file
- An option to have the conversation log emailed to you at the end of the session

Any combination of the above would work.

**Comment by aidanLarock** [comment]
Chose to use a copy chat log button. This allows the user to copy and paste the chat as they wish. This will allow users to paste information given by the bot to further look up or research such as directions or players.
