### ISSUE TITLE
As a user, I want there to be a button to clear my typed input instantly so that I don't have to hold down the backspace key.

### ISSUE THREAD

**Issue by Braden-Saunders** [Drov3r/COSC-4P02#32]
Section: 4.13.1
Priority level: 7

"As with many chat-based software, having a way to clear typed text without sending it or manually deleting it is a valued and useful feature. The clear input button is a simple feature, but a useful quality of life capability that will enhance the user experience of the software."

"This works best as a simple button on the software, located near the input bar, however, away from the button used to send, to avoid mis-clicks accidentally deleting questions. The button should also be clearly identified as a clearing button, so it cannot be confused with the send button."

**Comment by aidanLarock** [comment]
Clear button is located near the enter message bar, but on the opposite side. Button correctly clears any input the user has entered.
