### ISSUE TITLE
As a developer, I want a word processor that will take an input string and understand the query through analysis and pass the key information to the Data Collection process.

### ISSUE THREAD

**Issue by JJMGula** [Drov3r/COSC-4P02#52]

**Comment by JJMGula** [comment]
Information from original output and the info determined by the processor should be pushed to next step (Data Collection and Database)

**Comment by JJMGula** [comment]
Priority == 9.5 (Understanding user request)

**Comment by Braden-Saunders** [comment]
Related to #54. Added with c597a9c2f3764a5c93252262d0475a10e2a06db5.
