### ISSUE TITLE
As a company, i want the components to be self contained so that seperate components cannot be compromised

### ISSUE THREAD

**Issue by aidanLarock** [Drov3r/COSC-4P02#53]

**Comment by aidanLarock** [comment]
Priority: 10

**Comment by Drov3r** [comment]
All systems can be run in different machines. the website needs to be hosted by Apache and have the following ports open HTTP HTTPS and 8080 open. The Database needs be accessible on port 5843 on the machine its running on. Requests to open NLP can be made to port 8080.
