### ISSUE TITLE
As a developer, I would like to receive some string/array from the language processor and identify what information is being requested so that the response can be generated based off the selected information.

### ISSUE THREAD

**Issue by JJMGula** [Drov3r/COSC-4P02#54]

**Comment by JJMGula** [comment]
Priority == 9.5 (No response without selected info)

**Comment by Braden-Saunders** [comment]
Test implementation working in bbad2f65c7d407a9d063f79d3a04a53aa61f7191.

**Comment by Braden-Saunders** [comment]
Added in c597a9c2f3764a5c93252262d0475a10e2a06db5. We can now extract the noun string out of the user input to pass over to the database handler, the database handler can then fetch the requested information.
