### ISSUE TITLE
As a user, I would like to receive a comprehensible response from the AI so that my request is solved/dealt with.

### ISSUE THREAD

**Issue by JJMGula** [Drov3r/COSC-4P02#55]

**Comment by JJMGula** [comment]
Priority == 10 (Can't have illegible response)

**Comment by Braden-Saunders** [comment]
Added with 30fc590777896802a1aae562df65cd5ac6dd762b and c597a9c2f3764a5c93252262d0475a10e2a06db5. Bot will categorize the user input question using OpenNLP and then respond accordingly.
