### ISSUE TITLE
As a user I would like to see locations, sports, times, dates of games competed in, and available scores so that I can be fully involved in the event.

### ISSUE THREAD

**Issue by DanielGannage** [Drov3r/COSC-4P02#58]

**Comment by griffinallen** [comment]
The chatbot can find locations, sports, times and dates of games competed in. The available scores can be scraped as well, but functionality has not been tested since there are no active scores in the site.

**Comment by aidanLarock** [comment]
Chat bot reverts to opening date if there are no current scores.
