### ISSUE TITLE
As the Canada Games owner, I want the accomodations data to be scraped daily with the accurate, non-biased data, so that users will can effectively plan their trip using the chatbot

### ISSUE THREAD

**Issue by griffinallen** [Drov3r/COSC-4P02#82]

**Comment by JJMGula** [comment]
To improve accuracy of the data we store in the database, It will be routinely checked (every day) for and discrepancies by comparing what is recently scraped to what is inside the database. If the data inside the database is not apart of the recently scraped data, it will be removed.
